### ISSUE TITLE
Enter Address:

### ISSUE THREAD

**Issue by iHaikal** [BlairMar/deliveroo-webscraping-team#2]
Enter 4 Address': Add as an input (NP this might be an issue discuss if it is)
Make sure to enter a road and not postcode.

**Comment by SiraajCh** [comment]
3 Scenarios based on address input:

1. Address is accurate i.e. door number and road given -> Goes straight to restaurants
2. Address is slightly vague i.e a building name (buckingham palace) -> shows map pin, but location can be marked without moving pin
3. Address is too vague i.e. just a road name (the location could be anywhere on that road!) -> forces you to move map pin before marking location.

I have managed to address the first 2 scenarios, however have failed in my attempts to move the pin as required for the third scenario

**Comment by iHaikal** [comment]
@SiraajCh -- I would ignore the third scenario for now.
